// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiamLkFHFpIrOPotSchxks0rcH6DjY5Ao',
    appId: '1:964392250849:web:0f419d79be854fc7a136a0',
    messagingSenderId: '964392250849',
    projectId: 'dam-pi-6b22c',
    authDomain: 'dam-pi-6b22c.firebaseapp.com',
    storageBucket: 'dam-pi-6b22c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA08Vv0uE4H_8Qvp1vcOl_kNbaVxeDTrZ8',
    appId: '1:964392250849:android:5afa54ce4a638ad5a136a0',
    messagingSenderId: '964392250849',
    projectId: 'dam-pi-6b22c',
    storageBucket: 'dam-pi-6b22c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDA0PJ7oFmeHRT90xUoGE3cjRgLFr7H8',
    appId: '1:964392250849:ios:2a218a6a4417aeb3a136a0',
    messagingSenderId: '964392250849',
    projectId: 'dam-pi-6b22c',
    storageBucket: 'dam-pi-6b22c.appspot.com',
    iosBundleId: 'com.test.pi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGDA0PJ7oFmeHRT90xUoGE3cjRgLFr7H8',
    appId: '1:964392250849:ios:5107955d39a9e4eda136a0',
    messagingSenderId: '964392250849',
    projectId: 'dam-pi-6b22c',
    storageBucket: 'dam-pi-6b22c.appspot.com',
    iosBundleId: 'com.test.pi.RunnerTests',
  );
}
